name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build and Publish
        run: |
          dotnet publish -c Release -o ./bin/release/net8.0
          cd ./bin/release/net8.0
          zip -r getChats.zip *

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Package the Lambda function
        run: dotnet publish -c Release -r linux-x64 --self-contained false -o ./bin/release/net8.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd ./
          terraform init

      - name: Terraform Apply
        run: |
          cd ./
          terraform apply -auto-approve
